### PR TITLE
added JPL

### PR DESCRIPTION
**Pull request by shlake**

### CODE REVIEW

**Comment by shlake** [comment]
Closes #185 

@ar062800 can you add an email for a contact. It is good to have for the Dataverse Team (Harvard) to contact us repo managers for timely "problems". 

Thx.

**Comment by ar062800** [comment]
Hello @shlake, I just wanted to clarify that this email will not be published on the website or on anything public, and it will only be for the Dataverse Team, correct?

Here is our main contact: aaron.curtis@jpl.nasa.gov

**Comment by pdurbin** [comment]
@ar062800 oh, sorry, yes, this email is public. I mean, this issue itself is public. And it get put at https://iqss.github.io/dataverse-installations/data/data.json . It would be better to have an email that isn't tied to a person, if possible. support@jpl.nasa.gov or whatever. Or we can make it blank for now and follow up with your installation later as part of this issue:

- #143

**Comment by pdurbin** [comment]
@ar062800 and I chatted today. They're in the process of setting up a new dedicated contact email and will get in touch when it's ready.

**Pull request merged**
