### PR TITLE
Testing marker clustering, fix some minors

### PR DESCRIPTION
**Pull request by poikilotherm**
Please see commit messages.
You can see it working at https://poikilotherm.github.io/dataverse-installations
Feedback appreciated.

### CODE REVIEW

**Comment by pdurbin** [comment]
@poikilotherm I especially like how you can click one of the clusters and it zooms in on it. I'll add a couple screenshots with an example of my clicking the "12" in Europe:

Dataverse_Installations_Around_the_World_-_2019-10-27_16 30 02

Dataverse_Installations_Around_the_World_-_2019-10-27_16 30 27

To reiterate, we can all play around with this version of the map at https://poikilotherm.github.io/dataverse-installations

Also, we should think about how we are no longer limited to a single map. We can have as many maps as we need! Thanks, @poikilotherm ! :smile:

**Comment by poikilotherm** [comment]
One might also play a bit with `maxClusterRadius` and see how reducing it influences the cluster placements.

**Comment by poikilotherm** [comment]
I played a bit with that radius and it seems like 70 is a sweet spot with our current installation markers.
That way, AUSSDA is not clustered with the ones from Middle East, which does reflect the Europe number better. It also seems to better cluster nearby installations on North + South America. Please see attached screenshot:

grafik

**Comment by pdurbin** [comment]
@shlake it looks like the pull request has already been merged. Should we establish more of a process? I'm up for whatever. 😄

**Comment by djbrooke** [comment]
@shlake @pdurbin - I merged this because I thought it looked great. I saw that Sherry did as well.

**Comment by poikilotherm** [comment]
Noise: I have been informed I made it through Hacktoberfest challenge. So thanks for merging on time :smile:

**Comment by djbrooke** [comment]
I'm going to revert this in https://github.com/IQSS/dataverse-installations/pull/21. My mistake to merge. We need a review from @TaniaSchlatter.

**Comment by TaniaSchlatter** [comment]
Thanks!

**Pull request merged**
