### PR TITLE
Change dataverse nl's info #33

### LINKED ISSUE #33: Update information on the map for DataverseNL
I have three changes for DataverseNL on the map. 
1. The harvesting set should be 'uvt_datasets' instead of 'tilburg_oai'. 
2. I changed the description in the spreadsheet into: 'DataverseNL is a data repository hosted by DANS. Researchers associated with the DataverseNL partners (Several universities, higher education and research institutes) are able to deposit data. '
3. Our location coordinates should be: latitude 52.0808304 longitude, 4.3456727

### PR DESCRIPTION
**Pull request by jggautier**
Closes #33

### CODE REVIEW

**Comment by shlake** [comment]
@pdurbin looks like @jggautier ran the python script? Or did @jggautier just edit the data/data.json file here on github?

I thought the lat-long and harvesting set name were in another file and that running the python script added that info to the data file - which might be what happed???

Because if the source files haven't been updated then running the python script will undo what @jggautier did (if he just edited the data file) - or is Sherry reading too much into this??

**Comment by pdurbin** [comment]
@shlake thanks for asking! I like the checks and balances. 😄 

First @jggautier updated the lat/long in https://services.dataverse.harvard.edu/miniverse/map/installations-json using the Django admin for the old/current miniverse map.

Then he ran the python script.

Then he took the JSON output from the pull request and made this pull request.

I coached him through it but he made it look easy. 😄 

If you're happy with all this, please feel free to merge!

**Comment by shlake** [comment]
Thanks @pdurbin. Originally you asked if I would ask Laura to run the script and do the pull.

**Comment by pdurbin** [comment]
@shlake whoops. You're right. I figured I'd give @jggautier a chance but here I encouraged Laura to make pull requests in the future: https://github.com/IQSS/dataverse-installations/issues/33#issuecomment-562229581 😄

**Pull request merged**
